syntax = "proto3";

package fact_api;

import "google/protobuf/timestamp.proto";

option cc_enable_arenas = true;

message Process {
  // A unique UUID for identifying the message
  // We have this here instead of at the top level
  // because we want to have each message to be
  // self contained.
  string id = 1;

  // ID of container associated with this process
  string container_id = 2;

  // Process creation time
  google.protobuf.Timestamp creation_time = 3;

  // Process name
  string name = 4;

  // Process arguments
  string args = 5;

  // Process executable file path
  string exec_file_path = 6;

  // Host process ID
  uint32 pid = 7;

  // Real user ID
  uint32 uid = 8;

  // Real group ID
  uint32 gid = 9;

  // Signal origin
  bool scraped = 10;

  // Process LineageInfo
  repeated LineageInfo lineage_info = 11;

  message LineageInfo {
    uint32 parent_uid = 1;
    string parent_exec_file_path = 2;
  }

  // SFA fields
  // User ID used for login to the system
  uint32 login_uid = 12;

  // string representation of the process uid
  string username = 13;

  // whether the process is running on the root mount namespace
  bool in_root_mount_ns = 14;
}

message ProcessFork {
  Process parent = 1;
  Process child = 2;
}

message ProcessActivity {
  oneof process {
    ProcessFork fork = 1;
    Process exec = 2;
    Process proc = 3;
  }
}
